"""Emit the decision-flip-rate figure as native TikZ, from the stored results.

The operator's rule is: a reading clears a threshold only if its whole 95%
interval lies above it, fails only if the whole interval lies below it, and is
undecided otherwise. Two readings of the same chain -- one carrying the
measured cross-link covariance, one declaring the cross-term zero -- therefore
disagree on a set of thresholds. This figure reports the size of that set.

Because both readings are centred on the same plug-in point h, the
disagreement set is the pair of shoulders
    [lo_measured, lo_zero)  and  (hi_zero, hi_measured],
of total length w_measured - w_zero. For a threshold window [h - d, h + d] the
flip rate is the fraction of that window on which the two readings differ. The
curve is plotted against d in units of the measured 95% half-width, so both
worked examples share one axis.

Every quantity is read from
    experiment/redraw-2026-07-24/results-redraw.json         (German credit)
    experiment/real-agentic-2026-07-25/results-real-agentic.json (real system)
Nothing is hard-coded. Writes the source copy in figures/ and the copy included
by article/.
"""

import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
RES_GC = ROOT / 'experiment' / 'redraw-2026-07-24' / 'results-redraw.json'
RES_RA = (ROOT / 'experiment' / 'real-agentic-2026-07-25'
          / 'results-real-agentic.json')
OUTS = (
    HERE / 'fig-flip-rate-tikz.tex',
    ROOT / 'article' / 'fig-flip-rate-tikz.tex',
)

WIDTH_MM = 100.0          # drawing width of the window axis
HEIGHT_MM = 48.0          # drawing height of the rate axis
UMAX = 3.0                # window half-width, in measured half-widths
FMAX = 26.0               # per cent
XTICKS = [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
YTICKS = [0, 5, 10, 15, 20, 25]
NSAMP = 240


def mmx(u):
    return u / UMAX * WIDTH_MM


def mmy(f):
    return f / FMAX * HEIGHT_MM


def flip_rate(u, r):
    """Fraction of the window [h-d, h+d] on which the two readings differ.

    u = d / (w_measured / 2);  r = w_zero / w_measured  (r < 1 when the
    declared-zero reading is the narrower one).
    """
    if u <= 0.0:
        return 0.0
    if u <= r:
        return 0.0
    if u <= 1.0:
        return 100.0 * (1.0 - r / u)
    return 100.0 * (1.0 - r) / u


def arm(chain, label, dashed):
    lo_m, hi_m = chain['ci95_measured_covariance']
    lo_z, hi_z = chain['ci95_cross_term_declared_zero']
    w_m = chain['width_measured']
    w_z = chain['width_declared_zero']
    r = w_z / w_m
    return {
        'label': label, 'dashed': dashed, 'r': r,
        'peak': 100.0 * (1.0 - r),
        'lo_m': lo_m, 'hi_m': hi_m, 'lo_z': lo_z, 'hi_z': hi_z,
        'w_m': w_m, 'w_z': w_z,
        'h': chain['h_point'],
        'under': chain['understatement_of_width_pct'],
    }


def polyline(a):
    """Sample the curve, forcing the two kinks at u = r and u = 1 onto it."""
    us = [i * UMAX / NSAMP for i in range(NSAMP + 1)]
    us += [a['r'], 1.0]
    us = sorted(set(u for u in us if 0.0 <= u <= UMAX))
    return [(u, flip_rate(u, a['r'])) for u in us]


def main():
    gc = json.loads(RES_GC.read_text())['chain']['redraw']
    ra = json.loads(RES_RA.read_text())['chain']['logit']['redraw']
    arms = [
        arm(gc, 'German-credit chain', False),
        arm(ra, 'real agentic chain', True),
    ]

    L = []
    add = L.append
    add('% Decision-flip rate for the two worked chains: the fraction of')
    add('% operator thresholds judged differently by the two readings.')
    add('% Generated by figures/make_fig_flip_rate_tikz.py from')
    add('% experiment/redraw-2026-07-24/results-redraw.json and')
    add('% experiment/real-agentic-2026-07-25/results-real-agentic.json')
    add('% -- do not edit by hand. Preamble needs: \\usepackage{tikz}')
    add('\\begin{tikzpicture}')
    add('')
    add('  % axes')
    add(f'  \\draw ({mmx(0):.2f}mm,{mmy(0):.2f}mm) -- '
        f'({mmx(UMAX):.2f}mm,{mmy(0):.2f}mm);')
    add(f'  \\draw ({mmx(0):.2f}mm,{mmy(0):.2f}mm) -- '
        f'({mmx(0):.2f}mm,{mmy(FMAX):.2f}mm);')
    for t in XTICKS:
        add(f'  \\draw ({mmx(t):.2f}mm,{mmy(0):.2f}mm) -- '
            f'({mmx(t):.2f}mm,{mmy(0) - 1.2:.2f}mm);')
        add(f'  \\node[anchor=north,font=\\scriptsize] at '
            f'({mmx(t):.2f}mm,{mmy(0) - 1.2:.2f}mm) {{${t:.1f}$}};')
    for t in YTICKS:
        add(f'  \\draw ({mmx(0):.2f}mm,{mmy(t):.2f}mm) -- '
            f'({mmx(0) - 1.2:.2f}mm,{mmy(t):.2f}mm);')
        add(f'  \\node[anchor=east,font=\\scriptsize] at '
            f'({mmx(0) - 1.2:.2f}mm,{mmy(t):.2f}mm) {{${t}$}};')
    add('')
    add('  % the window that is exactly the measured 95% interval')
    add(f'  \\draw[dotted] ({mmx(1.0):.2f}mm,{mmy(0):.2f}mm) -- '
        f'({mmx(1.0):.2f}mm,{mmy(FMAX):.2f}mm);')
    add('')
    for a in arms:
        style = 'thick,dashed' if a['dashed'] else 'thick'
        pts = ' -- '.join(f'({mmx(u):.2f}mm,{mmy(f):.2f}mm)'
                          for u, f in polyline(a))
        add(f'  % {a["label"]}: w_measured {a["w_m"]:.5f}, '
            f'w_declared_zero {a["w_z"]:.5f}, peak {a["peak"]:.2f}%')
        add(f'  \\draw[{style}] {pts};')
        add(f'  \\fill ({mmx(1.0):.2f}mm,{mmy(a["peak"]):.2f}mm) '
            f'circle (1.5pt);')
        add(f'  \\node[anchor=south west,font=\\scriptsize] at '
            f'({mmx(1.04):.2f}mm,{mmy(a["peak"]) + 1.0:.2f}mm) '
            f'{{${a["peak"]:.1f}\\%$}};')
        add('')

    add('  % legend, in the region both curves leave empty')
    for k, a in enumerate(arms):
        y = mmy(FMAX) - 3.0 - 5.0 * k
        style = 'thick,dashed' if a['dashed'] else 'thick'
        add(f'  \\draw[{style}] (4.0mm,{y:.2f}mm) -- (11.0mm,{y:.2f}mm);')
        add(f'  \\node[anchor=west,font=\\scriptsize] at '
            f'(12.0mm,{y:.2f}mm) {{{a["label"]}}};')
    add('')
    add('  % axis captions')
    add(f'  \\node[anchor=north,font=\\footnotesize] at '
        f'({mmx(UMAX / 2):.2f}mm,{mmy(0) - 6.0:.2f}mm)')
    add('    {threshold window half-width, in measured $95\\%$ half-widths};')
    add(f'  \\node[rotate=90,anchor=south,font=\\footnotesize] at '
        f'({mmx(0) - 7.5:.2f}mm,{mmy(FMAX / 2):.2f}mm)')
    add('    {thresholds judged differently (\\%)};')
    add('')
    add('\\end{tikzpicture}')
    add('')

    rendered = '\n'.join(L)
    for out in OUTS:
        out.write_text(rendered)
        print(f'wrote {out}')
    for a in arms:
        print(f'  {a["label"]}: h={a["h"]:.4f} '
              f'measured [{a["lo_m"]:.4f}, {a["hi_m"]:.4f}] '
              f'declared-zero [{a["lo_z"]:.4f}, {a["hi_z"]:.4f}]')
        print(f'    lower band [{a["lo_m"]:.4f}, {a["lo_z"]:.4f}] '
              f'width {a["lo_z"] - a["lo_m"]:.5f}; '
              f'upper band [{a["hi_z"]:.4f}, {a["hi_m"]:.4f}] '
              f'width {a["hi_m"] - a["hi_z"]:.5f}')
        print(f'    total disagreement length {a["w_m"] - a["w_z"]:.5f}; '
              f'peak flip rate {a["peak"]:.3f}% '
              f'(stored understatement {a["under"]:.3f}%)')
        for u in (0.5, 1.0, 1.5, 2.0, 3.0):
            print(f'    u={u:.1f}  flip rate {flip_rate(u, a["r"]):6.3f}%')


if __name__ == '__main__':
    main()
