"""Emit the chain-interval figure as native TikZ, from the redraw results.

Writes the source copy in figures/ and the copy included by article/. Every
quantity except the illustrative threshold is read from
experiment/redraw-2026-07-24/results-redraw.json; nothing is hard-coded.
"""

import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
RESULTS = ROOT / 'experiment' / 'redraw-2026-07-24' / 'results-redraw.json'
OUTS = (
    HERE / 'fig-chain-interval-tikz.tex',
    ROOT / 'article' / 'fig-chain-interval-tikz.tex',
)

WIDTH_MM = 105.0          # drawing width of the value axis
XMIN, XMAX = 0.775, 0.885
TICKS = [0.78, 0.80, 0.82, 0.84, 0.86, 0.88]


def mm(value):
    """Map a compliance value onto the drawing axis, in millimetres."""
    return (value - XMIN) / (XMAX - XMIN) * WIDTH_MM


def main():
    chain = json.loads(RESULTS.read_text())['chain']['redraw']
    lo_m, hi_m = chain['ci95_measured_covariance']
    lo_n, hi_n = chain['ci95_cross_term_declared_zero']
    point = chain['h_point']
    w_m = chain['width_measured']
    w_n = chain['width_declared_zero']
    under = chain['understatement_of_width_pct']
    rho = chain['cross_link_correlation']

    # The threshold is chosen, not measured: the midpoint of the two lower
    # endpoints, so that (a) straddles it and (b) clears it. Stated as
    # illustrative in the figure, in the caption and in the text.
    thr = round(0.5 * (lo_m + lo_n), 3)
    assert lo_m < thr < lo_n, 'the illustrative threshold must separate the two readings'

    L = []
    add = L.append
    add('% Composed compliance figure on the two-link chain: the 95% interval with the')
    add('% measured cross-link covariance, and with the cross-term declared zero.')
    add('% Generated by figures/make_fig_chain_interval_tikz.py from')
    add('% experiment/redraw-2026-07-24/results-redraw.json -- do not edit by hand.')
    add('% Preamble needs: \\usepackage{tikz} \\usetikzlibrary{patterns}')
    add('\\begin{tikzpicture}[y=10mm]')
    add('')
    add('  % hatched band: the thresholds the two readings judge differently')
    add(f'  \\fill[pattern=north east lines, pattern color=black!45]')
    add(f'    ({mm(lo_m):.2f}mm,-1.70) rectangle ({mm(lo_n):.2f}mm,1.45);')
    add(f'  \\draw[dotted] ({mm(lo_m):.2f}mm,-1.70) -- ({mm(lo_m):.2f}mm,1.45);')
    add(f'  \\draw[dotted] ({mm(lo_n):.2f}mm,-1.70) -- ({mm(lo_n):.2f}mm,1.45);')
    add('')
    add('  % illustrative operator threshold')
    add(f'  \\draw[thick] ({mm(thr):.2f}mm,-1.80) -- ({mm(thr):.2f}mm,1.62);')
    add(f'  \\node[anchor=south,font=\\footnotesize] at ({mm(thr):.2f}mm,1.62)')
    add(f'    {{operator threshold ${thr:.3f}$ (illustrative)}};')
    add('')
    add('  % (a) measured cross-link covariance')
    add(f'  \\draw[thick] ({mm(lo_m):.2f}mm,0.85) -- ({mm(hi_m):.2f}mm,0.85);')
    add(f'  \\draw[thick] ({mm(lo_m):.2f}mm,0.58) -- ({mm(lo_m):.2f}mm,1.12);')
    add(f'  \\draw[thick] ({mm(hi_m):.2f}mm,0.58) -- ({mm(hi_m):.2f}mm,1.12);')
    add(f'  \\fill ({mm(point):.2f}mm,0.85) circle (1.7pt);')
    add(f'  \\node[anchor=east,font=\\footnotesize,align=right] at ({mm(lo_m) - 4:.2f}mm,0.85)')
    add('    {(a) measured\\\\cross-link\\\\covariance};')
    add(f'  \\node[anchor=south,font=\\scriptsize] at ({mm(point):.2f}mm,1.05)')
    add(f'    {{point estimate ${point:.3f}$, width ${w_m:.4f}$}};')
    add(f'  \\node[anchor=north,font=\\scriptsize] at ({mm(point):.2f}mm,0.60)')
    add('    {straddles the threshold: undecided};')
    add('')
    add('  % (b) cross-term declared zero')
    add(f'  \\draw[thick,dashed] ({mm(lo_n):.2f}mm,-1.05) -- ({mm(hi_n):.2f}mm,-1.05);')
    add(f'  \\draw[thick] ({mm(lo_n):.2f}mm,-1.25) -- ({mm(lo_n):.2f}mm,-0.85);')
    add(f'  \\draw[thick] ({mm(hi_n):.2f}mm,-1.25) -- ({mm(hi_n):.2f}mm,-0.85);')
    add(f'  \\draw ({mm(point):.2f}mm,-1.05) circle (1.7pt);')
    add(f'  \\node[anchor=east,font=\\footnotesize,align=right] at ({mm(lo_m) - 4:.2f}mm,-1.05)')
    add('    {(b) cross-term\\\\declared zero};')
    add(f'  \\node[anchor=south,font=\\scriptsize] at ({mm(point) + 5:.2f}mm,-0.87)')
    add(f'    {{width ${w_n:.4f}$, understating it by ${under:.1f}$ per cent}};')
    add(f'  \\node[anchor=north,font=\\scriptsize] at ({mm(point):.2f}mm,-1.27)')
    add('    {clear of the threshold: reads as passing};')
    add('')
    add('  % band annotation')
    add(f'  \\node[anchor=north,font=\\scriptsize] at ({mm(point):.2f}mm,-1.78)')
    add('    {any threshold in the hatched band: (a) is undecided, (b) passes};')
    add('')
    add('  % value axis')
    add(f'  \\draw ({mm(XMIN):.2f}mm,-2.30) -- ({mm(XMAX):.2f}mm,-2.30);')
    for t in TICKS:
        add(f'  \\draw ({mm(t):.2f}mm,-2.30) -- ({mm(t):.2f}mm,-2.42);')
        add(f'  \\node[anchor=north,font=\\scriptsize] at ({mm(t):.2f}mm,-2.42) {{${t:.2f}$}};')
    add(f'  \\node[anchor=north,font=\\footnotesize] at ({mm(0.83):.2f}mm,-2.92)')
    add('    {composed compliance figure $h = C(\\mathrm{logit}) \\times C(\\mathrm{rf})$};')
    add('')
    add('\\end{tikzpicture}')
    add('')

    rendered = '\n'.join(L)
    for out in OUTS:
        out.write_text(rendered)
        print(f'wrote {out}')
    print(f'  point {point:.4f}  measured [{lo_m:.4f}, {hi_m:.4f}]  naive [{lo_n:.4f}, {hi_n:.4f}]')
    print(f'  widths {w_m:.5f} vs {w_n:.5f}, understatement {under:.2f}%, rho {rho:.4f}')
    print(f'  illustrative threshold {thr:.3f}')


if __name__ == '__main__':
    main()
