"""Emit the certificate worked-example figure as native TikZ.

One interval bar -- the composed score and its 95% interval exactly as the
example certificate records them -- screened against two policy thresholds:
one the interval clears (allow) and one that falls inside it (escalate).
Every quantity except the two illustrative thresholds is read from
experiment/certificate-examples/real-chain.json; nothing is hard-coded.
"""

import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
CERT = ROOT / 'experiment' / 'certificate-examples' / 'real-chain.json'
OUTS = (
    HERE / 'fig-cert-example-tikz.tex',
    ROOT / 'article' / 'fig-cert-example-tikz.tex',
)

WIDTH_MM = 105.0          # drawing width of the value axis
XMIN, XMAX = 0.735, 0.865
TICKS = [0.74, 0.76, 0.78, 0.80, 0.82, 0.84, 0.86]

# Chosen, not measured: a threshold the whole interval clears, and one that
# falls inside the interval. Stated as illustrative in the figure and text.
THR_ALLOW = 0.75
THR_ESC = 0.80


def mm(value):
    """Map a compliance value onto the drawing axis, in millimetres."""
    return (value - XMIN) / (XMAX - XMIN) * WIDTH_MM


def main():
    cert = json.loads(CERT.read_text())['certificate']
    meas = cert['measurement']['composed_score']
    point = meas['value']
    lo, hi = meas['interval95']
    est = cert['estimation']
    recal = cert['validity']['recalibrate_by_utc'][:10]

    # the sentences in Section 3.4 quote these figures; keep them honest
    assert round(point, 3) == 0.808
    assert (round(lo, 3), round(hi, 3)) == (0.768, 0.847)
    assert est['replicates'] == 2000
    assert lo >= THR_ALLOW, 'the allow threshold must be cleared by the interval'
    assert lo < THR_ESC < hi, 'the escalate threshold must fall inside the interval'

    L = []
    add = L.append
    add('% Certificate worked example: the certified composed score with its 95%')
    add('% interval, screened against an illustrative allow and escalate threshold.')
    add('% Generated by figures/make_fig_cert_example_tikz.py from')
    add('% experiment/certificate-examples/real-chain.json -- do not edit by hand.')
    add('% Preamble needs: \\usepackage{tikz}')
    add('\\begin{tikzpicture}[y=10mm]')
    add('')
    add('  % threshold the interval clears: allow')
    add(f'  \\draw[thick] ({mm(THR_ALLOW):.2f}mm,-0.95) -- ({mm(THR_ALLOW):.2f}mm,0.95);')
    add(f'  \\node[anchor=south,font=\\scriptsize,align=center] at ({mm(THR_ALLOW):.2f}mm,0.95)')
    add(f'    {{policy threshold ${THR_ALLOW:.2f}$\\\\interval clear: allow}};')
    add('')
    add('  % threshold inside the interval: escalate')
    add(f'  \\draw[thick,dashed] ({mm(THR_ESC):.2f}mm,-0.95) -- ({mm(THR_ESC):.2f}mm,0.95);')
    add(f'  \\node[anchor=south,font=\\scriptsize,align=center] at ({mm(THR_ESC):.2f}mm,0.95)')
    add(f'    {{policy threshold ${THR_ESC:.2f}$\\\\inside the interval: escalate}};')
    add('')
    add('  % the certified interval')
    add(f'  \\draw[thick] ({mm(lo):.2f}mm,0.00) -- ({mm(hi):.2f}mm,0.00);')
    add(f'  \\draw[thick] ({mm(lo):.2f}mm,-0.27) -- ({mm(lo):.2f}mm,0.27);')
    add(f'  \\draw[thick] ({mm(hi):.2f}mm,-0.27) -- ({mm(hi):.2f}mm,0.27);')
    add(f'  \\fill ({mm(point):.2f}mm,0.00) circle (1.7pt);')
    add(f'  \\node[anchor=north,font=\\scriptsize] at ({mm(point):.2f}mm,-0.32)')
    add(f'    {{certified composed score ${point:.3f}$, 95\\% interval $[{lo:.3f}, {hi:.3f}]$}};')
    add('')
    add('  % value axis')
    add(f'  \\draw ({mm(XMIN):.2f}mm,-1.30) -- ({mm(XMAX):.2f}mm,-1.30);')
    for t in TICKS:
        add(f'  \\draw ({mm(t):.2f}mm,-1.30) -- ({mm(t):.2f}mm,-1.42);')
        add(f'  \\node[anchor=north,font=\\scriptsize] at ({mm(t):.2f}mm,-1.42) {{${t:.2f}$}};')
    add(f'  \\node[anchor=north,font=\\footnotesize] at ({mm(0.80):.2f}mm,-1.92)')
    add(f'    {{paired bootstrap, $B = 2000$; recalibrate by {recal}}};')
    add('')
    add('\\end{tikzpicture}')
    add('')

    rendered = '\n'.join(L)
    for out in OUTS:
        out.write_text(rendered)
        print(f'wrote {out}')
    print(f'  point {point:.4f}  interval [{lo:.4f}, {hi:.4f}]')
    print(f'  thresholds: allow {THR_ALLOW}  escalate {THR_ESC}  recalibrate {recal}')


if __name__ == '__main__':
    main()
